# Generated by Django 2.2.12 on 2021-04-26 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210418_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime.today, null=True),
        ),
    ]
