# Generated by Django 2.2.12 on 2021-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210426_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
